spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/planapp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
      username: root
      password: shark1234
      driver-class-name: com.mysql.cj.jdbc.Driver